name: Frontend CI

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test -- --watchAll=false
      - name: Build
        run: npm run build
